# Website Settings
title: Grace Baro
description: Data Science & Research Portfolio
author: Grace Baro

# Theme
remote_theme: mmistakes/minimal-mistakes

# Social Links
github_username: Dayo-hub700

# Build Settings
markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Site Settings
locale: en-US
timezone: Africa/Lagos

name: Grace Baro
search: true
breadcrumbs: true

permalink: /:categories/:title/

repository: Dayo-hub700/Portfolio
